/**
 * Definitions and Metadata for the 10 Cardio & Bodyweight Exercises
 */

import { ExerciseDefinition, ExerciseId } from './poseTypes';

export const EXERCISE_DEFINITIONS: Record<ExerciseId, ExerciseDefinition> = {
  jumping_jacks: {
    id: 'jumping_jacks',
    name: 'Jumping Jacks',
    category: 'Cardio',
    targetMuscles: ['Calves', 'Deltoids', 'Glutes', 'Core'],
    calorieBurnPerRep: 0.22,
    estimatedMets: 8.0,
    instructions: [
      'Stand upright with feet together and arms at your sides.',
      'Jump out spreading feet wider than shoulder width while swinging arms above head.',
      'Jump back to starting neutral position with arms down.',
    ],
    tips: [
      'Keep your core braced throughout.',
      'Land softly on the balls of your feet.',
      'Raise hands fully above eye level on each jump.',
    ],
    recommendedReps: 25,
    recommendedSets: 3,
    restSeconds: 30,
    iconName: 'Activity',
  },
  squats: {
    id: 'squats',
    name: 'Bodyweight Squats',
    category: 'Strength',
    targetMuscles: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
    calorieBurnPerRep: 0.35,
    estimatedMets: 5.5,
    instructions: [
      'Stand with feet shoulder-width apart, toes pointed slightly outward.',
      'Hinge at hips and bend knees until thighs are parallel to ground (knee angle <= 95°).',
      'Drive through heels and return to fully upright standing position (knee angle >= 165°).',
    ],
    tips: [
      'Keep chest up and spine neutral.',
      'Avoid letting knees collapse inward.',
      'Descend to parallel or below for a full rep.',
    ],
    recommendedReps: 15,
    recommendedSets: 3,
    restSeconds: 45,
    iconName: 'TrendingDown',
  },
  high_knees: {
    id: 'high_knees',
    name: 'High Knees',
    category: 'Cardio',
    targetMuscles: ['Hip Flexors', 'Quadriceps', 'Calves', 'Abs'],
    calorieBurnPerRep: 0.18,
    estimatedMets: 8.5,
    instructions: [
      'Stand tall with feet hip-width apart.',
      'Drive one knee upward above hip level while pumping opposite arm.',
      'Alternate rapidly between left and right knees in a running rhythm (1 pair = 1 rep).',
    ],
    tips: [
      'Drive knees up to waist height.',
      'Maintain an upright athletic posture.',
      'Keep pace brisk and explosive.',
    ],
    recommendedReps: 30,
    recommendedSets: 3,
    restSeconds: 30,
    iconName: 'Zap',
  },
  mountain_climbers: {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    category: 'Core',
    targetMuscles: ['Core & Abs', 'Shoulders', 'Chest', 'Hip Flexors'],
    calorieBurnPerRep: 0.20,
    estimatedMets: 8.0,
    instructions: [
      'Start in a solid high plank position with shoulders stacked over wrists.',
      'Drive one knee forward toward your chest, keeping hips level.',
      'Quickly switch legs, extending back to plank and driving opposite knee.',
    ],
    tips: [
      'Keep your back flat and prevent hips from sagging.',
      'Drive knees forward with power.',
      'Maintain steady breathing rhythm.',
    ],
    recommendedReps: 20,
    recommendedSets: 3,
    restSeconds: 30,
    iconName: 'Flame',
  },
  burpees: {
    id: 'burpees',
    name: 'Burpees',
    category: 'Cardio',
    targetMuscles: ['Full Body', 'Chest', 'Quads', 'Shoulders', 'Cardiovascular'],
    calorieBurnPerRep: 0.65,
    estimatedMets: 9.5,
    instructions: [
      'From standing, drop into a squat and place hands on the floor.',
      'Kick feet back into a plank and drop hips/chest toward ground.',
      'Snap feet forward and explode up into a vertical jump with arms overhead.',
    ],
    tips: [
      'Maintain rhythm rather than rushing.',
      'Jump vertically with arms reaching past head.',
      'Land softly and transition smoothly into next rep.',
    ],
    recommendedReps: 10,
    recommendedSets: 3,
    restSeconds: 60,
    iconName: 'Sparkles',
  },
  butt_kicks: {
    id: 'butt_kicks',
    name: 'Butt Kicks',
    category: 'Cardio',
    targetMuscles: ['Hamstrings', 'Glutes', 'Calves'],
    calorieBurnPerRep: 0.16,
    estimatedMets: 7.5,
    instructions: [
      'Stand upright with feet hip-width apart.',
      'Kick heel up toward your glute (knee flexion <= 60°).',
      'Alternate legs in a quick, continuous jogging rhythm.',
    ],
    tips: [
      'Keep thighs relatively stationary while flexing knees.',
      'Focus on hamstring contraction.',
      'Maintain an upright torso.',
    ],
    recommendedReps: 30,
    recommendedSets: 3,
    restSeconds: 30,
    iconName: 'Footprints',
  },
  skater_jumps: {
    id: 'skater_jumps',
    name: 'Skater Jumps',
    category: 'Agility',
    targetMuscles: ['Glute Medius', 'Quadriceps', 'Calves', 'Ankle Stabilizers'],
    calorieBurnPerRep: 0.28,
    estimatedMets: 8.0,
    instructions: [
      'Start in a slight squat and bound sideways off one foot to the other side.',
      'Land softly on the outer foot with back leg sweeping behind in a skater stance.',
      'Immediately explode sideways in the opposite direction.',
    ],
    tips: [
      'Load your hip and spring laterally with power.',
      'Maintain balance and control on each landing.',
      'Sweep arms across body for momentum.',
    ],
    recommendedReps: 20,
    recommendedSets: 3,
    restSeconds: 40,
    iconName: 'Compass',
  },
  lunges: {
    id: 'lunges',
    name: 'Forward Lunges',
    category: 'Strength',
    targetMuscles: ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves'],
    calorieBurnPerRep: 0.32,
    estimatedMets: 5.5,
    instructions: [
      'Step forward with one leg and lower hips until front knee is at ~90°.',
      'Keep front knee tracked over ankle and rear knee hovering just above floor.',
      'Push forcefully off the front heel to return to neutral standing posture.',
    ],
    tips: [
      'Keep torso upright and shoulders back.',
      'Avoid leaning chest forward over front knee.',
      'Alternate legs smoothly.',
    ],
    recommendedReps: 16,
    recommendedSets: 3,
    restSeconds: 45,
    iconName: 'ArrowDownUp',
  },
  shadow_boxing: {
    id: 'shadow_boxing',
    name: 'Shadow Boxing (Jab/Cross)',
    category: 'Agility',
    targetMuscles: ['Shoulders', 'Triceps', 'Core', 'Lats'],
    calorieBurnPerRep: 0.15,
    estimatedMets: 7.0,
    instructions: [
      'Assume boxing guard stance with hands protecting chin (elbow angle <= 75°).',
      'Extend lead arm fully into a sharp jab or cross punch (elbow angle >= 160°).',
      'Snap hand back rapidly to tight guard position.',
    ],
    tips: [
      'Rotate hips and shoulders into the punch.',
      'Snap punches back quickly to defensive guard.',
      'Keep knees soft and stay light on feet.',
    ],
    recommendedReps: 30,
    recommendedSets: 3,
    restSeconds: 30,
    iconName: 'Shield',
  },
  standing_crunches: {
    id: 'standing_crunches',
    name: 'Standing Oblique Crunches',
    category: 'Core',
    targetMuscles: ['Obliques', 'Abs', 'Hip Flexors'],
    calorieBurnPerRep: 0.20,
    estimatedMets: 5.0,
    instructions: [
      'Stand with feet shoulder-width apart, hands placed lightly behind head.',
      'Lift knee outward laterally while crunching same-side elbow down toward knee.',
      'Squeeze oblique muscle, then extend fully back to neutral standing posture.',
    ],
    tips: [
      'Focus on side-body crunch compression.',
      'Avoid pulling on your neck with hands.',
      'Control both the upward drive and lowering phase.',
    ],
    recommendedReps: 20,
    recommendedSets: 3,
    restSeconds: 30,
    iconName: 'Dna',
  },
};

export const ALL_EXERCISE_LIST = Object.values(EXERCISE_DEFINITIONS);
