/**
 * Gemini Flash AI Nutrition Engine
 * Powered by Google AI Studio Gemini Flash for lightning-fast multimodal food vision & macro analysis.
 */

export interface DetectedFoodItem {
  item: string;
  portion: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
}

export interface GeminiMealNutrition {
  meal_name: string;
  meal_type: 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack';
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  fiber: number;
  confidence: 'High' | 'Medium' | 'Low';
  breakdown: DetectedFoodItem[];
  health_tip: string;
  summary: string;
}

const getGeminiApiKey = (): string => {
  const key =
    process.env.EXPO_PUBLIC_GEMINI_API_KEY ||
    (typeof process !== 'undefined' && process.env ? (process.env as any).EXPO_PUBLIC_GEMINI_API_KEY : '') ||
    'AIzaSyBRIIzjDvFfcht2G443mSxOw3sszAlFY7k';
  
  if (!key) {
    console.warn('[GeminiNutrition] EXPO_PUBLIC_GEMINI_API_KEY is not defined in environment variables.');
  }
  return key || '';
};

// Available Gemini Flash models in priority order
const GEMINI_MODELS = ['gemini-3.6-flash', 'gemini-3.7-flash', 'gemini-3.5-flash', 'gemini-3.5-flash-lite'];

/**
 * Helper to call Gemini REST API with fallback to alternative Flash models if needed.
 */
async function callGeminiApi(payload: any): Promise<string> {
  const apiKey = getGeminiApiKey();
  if (!apiKey) {
    throw new Error('Google AI Studio API Key is missing. Please set EXPO_PUBLIC_GEMINI_API_KEY in .env.');
  }

  let lastError: any = null;

  for (const model of GEMINI_MODELS) {
    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errorText = await res.text();
        console.warn(`[GeminiNutrition] Model ${model} returned ${res.status}: ${errorText}`);
        lastError = new Error(`Gemini API error (${res.status}): ${errorText}`);
        continue; // Try next model
      }

      const data = await res.json();
      const candidateText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!candidateText) {
        throw new Error('No response text generated by Gemini model.');
      }

      return candidateText;
    } catch (err: any) {
      lastError = err;
    }
  }

  throw lastError || new Error('Failed to analyze with Gemini Flash.');
}

/**
 * Clean & parse JSON response from Gemini
 */
function extractAndParseJson<T>(rawText: string, fallback: T): T {
  try {
    let clean = rawText.trim();
    // Strip markdown code fences if present (```json ... ```)
    if (clean.startsWith('```')) {
      clean = clean.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
    }
    return JSON.parse(clean) as T;
  } catch (err) {
    console.warn('[GeminiNutrition] JSON parse error on output:', rawText, err);
    return fallback;
  }
}

/**
 * Infer meal category based on current local hour
 */
export function getMealTypeByCurrentTime(): 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack' {
  const hour = new Date().getHours();
  if (hour >= 5 && hour < 11) return 'Breakfast';
  if (hour >= 11 && hour < 16) return 'Lunch';
  if (hour >= 16 && hour < 22) return 'Dinner';
  return 'Snack';
}

/**
 * 1. Analyze Food Image with Gemini Flash Multimodal Vision
 * @param base64Data Base64-encoded image string (without data:image/... prefix or with it)
 * @param mimeType e.g. 'image/jpeg' or 'image/png'
 */
export async function analyzeFoodImageWithGemini(
  base64Data: string,
  mimeType: string = 'image/jpeg'
): Promise<GeminiMealNutrition> {
  // Strip any data URI header if present
  const cleanBase64 = base64Data.includes('base64,')
    ? base64Data.split('base64,')[1]
    : base64Data;

  const defaultCategory = getMealTypeByCurrentTime();

  const promptText = `
You are an expert sports nutritionist and computer vision food AI.
Analyze this meal photo carefully:
1. Identify all recognizable food and drink items on the plate or table.
2. Estimate the visual portion weights/sizes based on typical tableware and geometry.
3. Calculate accurate nutritional facts: Total Calories (kcal), Protein (g), Carbohydrates (g), Fats (g), and Dietary Fiber (g).
4. Categorize the meal type ('Breakfast', 'Lunch', 'Dinner', or 'Snack').
5. Provide a short, motivating athletic health/nutrition tip.

You MUST respond ONLY with a strictly valid JSON object adhering to this schema (no extra text, no markdown explanation outside the JSON):
{
  "meal_name": "Concise Descriptive Food Name (e.g. Grilled Chicken Bowl with Brown Rice & Avocado)",
  "meal_type": "${defaultCategory}",
  "calories": 550,
  "protein": 42,
  "carbs": 50,
  "fats": 16,
  "fiber": 6,
  "confidence": "High",
  "breakdown": [
    { "item": "Grilled Chicken Breast", "portion": "150g", "calories": 240, "protein": 38, "carbs": 0, "fats": 5 },
    { "item": "Cooked Brown Rice", "portion": "1 cup (150g)", "calories": 160, "protein": 3, "carbs": 34, "fats": 1 },
    { "item": "Avocado & Veggies", "portion": "100g", "calories": 150, "protein": 1, "carbs": 16, "fats": 10 }
  ],
  "health_tip": "High protein ratio optimal for muscle protein synthesis and sustained energy.",
  "summary": "150g chicken breast, 1 cup brown rice with avocado and steamed veggies"
}
`;

  const payload = {
    contents: [
      {
        parts: [
          { text: promptText },
          {
            inline_data: {
              mime_type: mimeType,
              data: cleanBase64,
            },
          },
        ],
      },
    ],
    generationConfig: {
      temperature: 0.2,
      topK: 32,
      topP: 0.95,
      maxOutputTokens: 1024,
      response_mime_type: 'application/json',
    },
  };

  const rawOutput = await callGeminiApi(payload);

  const fallback: GeminiMealNutrition = {
    meal_name: 'Identified Meal',
    meal_type: defaultCategory,
    calories: 450,
    protein: 25,
    carbs: 45,
    fats: 15,
    fiber: 4,
    confidence: 'Medium',
    breakdown: [{ item: 'Assorted Meal Items', portion: '1 plate', calories: 450, protein: 25, carbs: 45, fats: 15 }],
    health_tip: 'Nutrient-rich meal logged via AI Vision.',
    summary: 'Analyzed food plate',
  };

  const parsed = extractAndParseJson<GeminiMealNutrition>(rawOutput, fallback);

  // Normalize numbers to prevent NaN or unexpected types
  return {
    meal_name: String(parsed.meal_name || 'Logged Meal').trim(),
    meal_type: (['Breakfast', 'Lunch', 'Dinner', 'Snack'].includes(parsed.meal_type)
      ? parsed.meal_type
      : defaultCategory) as any,
    calories: Math.round(Number(parsed.calories) || 0),
    protein: Math.round(Number(parsed.protein) || 0),
    carbs: Math.round(Number(parsed.carbs) || 0),
    fats: Math.round(Number(parsed.fats) || 0),
    fiber: Math.round(Number(parsed.fiber) || 0),
    confidence: (['High', 'Medium', 'Low'].includes(parsed.confidence) ? parsed.confidence : 'High') as any,
    breakdown: Array.isArray(parsed.breakdown) ? parsed.breakdown : [],
    health_tip: String(parsed.health_tip || 'Balanced nutrition profile.').trim(),
    summary: String(parsed.summary || parsed.meal_name || '').trim(),
  };
}

/**
 * 2. Analyze Meal from Natural Text Description with Gemini Flash
 * @param description e.g. "2 boiled eggs with 2 slices of whole grain bread and 1 cup of Greek yogurt"
 */
export async function analyzeMealTextWithGemini(
  description: string
): Promise<GeminiMealNutrition> {
  const defaultCategory = getMealTypeByCurrentTime();

  const promptText = `
You are an expert sports nutritionist AI.
Analyze the user's meal description: "${description}"
1. Breakdown all food ingredients and quantities.
2. Calculate accurate nutritional facts: Total Calories (kcal), Protein (g), Carbohydrates (g), Fats (g), and Dietary Fiber (g).
3. Infer the best meal type category ('Breakfast', 'Lunch', 'Dinner', or 'Snack').
4. Provide a short, motivating athletic health/nutrition tip.

You MUST respond ONLY with a strictly valid JSON object adhering to this schema (no extra text, no markdown explanation outside the JSON):
{
  "meal_name": "Standardized Meal Title",
  "meal_type": "${defaultCategory}",
  "calories": 400,
  "protein": 30,
  "carbs": 35,
  "fats": 12,
  "fiber": 5,
  "confidence": "High",
  "breakdown": [
    { "item": "Item 1", "portion": "qty", "calories": 200, "protein": 15, "carbs": 20, "fats": 6 }
  ],
  "health_tip": "High protein meal aiding muscle recovery and satiety.",
  "summary": "Short ingredient breakdown"
}
`;

  const payload = {
    contents: [
      {
        parts: [{ text: promptText }],
      },
    ],
    generationConfig: {
      temperature: 0.1,
      topK: 32,
      topP: 0.95,
      maxOutputTokens: 1024,
      response_mime_type: 'application/json',
    },
  };

  const rawOutput = await callGeminiApi(payload);

  const fallback: GeminiMealNutrition = {
    meal_name: description,
    meal_type: defaultCategory,
    calories: 350,
    protein: 20,
    carbs: 40,
    fats: 10,
    fiber: 3,
    confidence: 'Medium',
    breakdown: [{ item: description, portion: '1 serving', calories: 350, protein: 20, carbs: 40, fats: 10 }],
    health_tip: 'Good energy balance for daily performance.',
    summary: description,
  };

  const parsed = extractAndParseJson<GeminiMealNutrition>(rawOutput, fallback);

  return {
    meal_name: String(parsed.meal_name || description).trim(),
    meal_type: (['Breakfast', 'Lunch', 'Dinner', 'Snack'].includes(parsed.meal_type)
      ? parsed.meal_type
      : defaultCategory) as any,
    calories: Math.round(Number(parsed.calories) || 0),
    protein: Math.round(Number(parsed.protein) || 0),
    carbs: Math.round(Number(parsed.carbs) || 0),
    fats: Math.round(Number(parsed.fats) || 0),
    fiber: Math.round(Number(parsed.fiber) || 0),
    confidence: (['High', 'Medium', 'Low'].includes(parsed.confidence) ? parsed.confidence : 'High') as any,
    breakdown: Array.isArray(parsed.breakdown) ? parsed.breakdown : [],
    health_tip: String(parsed.health_tip || 'Nutrient profile balanced.').trim(),
    summary: String(parsed.summary || description).trim(),
  };
}
